app:
  - redirects:
      - from: /manifest.json
        to: /manifest.json
        cdn: true
      - from: /*
        to: /index.html
        assets: false
      - from: "/auth*"
        to: "/auth"
        assets": false
